# Generated by Django 4.2.3 on 2023-08-17 01:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apptelovendo', '0002_alter_customuser_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='username',
        ),
    ]
