# Generated by Django 4.2.4 on 2023-09-07 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apptelovendo', '0007_pedido_asignado_a_alter_pedido_usuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='detallepedido',
            name='despacho',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
