# Generated by Django 4.2.4 on 2023-09-08 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apptelovendo', '0008_detallepedido_despacho'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detallepedido',
            name='despacho',
        ),
        migrations.AddField(
            model_name='pedido',
            name='despacho',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
