# Generated by Django 4.2.4 on 2023-09-08 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apptelovendo', '0009_remove_detallepedido_despacho_pedido_despacho'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='forma_pago',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
