# Generated by Django 4.2.4 on 2023-09-08 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apptelovendo', '0010_pedido_forma_pago'),
    ]

    operations = [
        migrations.AddField(
            model_name='detallepedido',
            name='cliente',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='detallepedido',
            name='despacho',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='detallepedido',
            name='forma_pago',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='detallepedido',
            name='precio',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
