# Generated by Django 4.2.4 on 2023-09-08 23:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apptelovendo', '0012_detallepedido_productos'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detallepedido',
            name='pedido',
        ),
        migrations.RemoveField(
            model_name='detallepedido',
            name='producto',
        ),
    ]
