# Generated by Django 4.2.4 on 2023-09-09 18:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apptelovendo', '0013_remove_detallepedido_pedido_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PedidoCliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direccion_entrega', models.CharField(max_length=250)),
                ('fecha_pedido', models.DateTimeField(auto_now_add=True)),
                ('forma_pago', models.CharField(max_length=100)),
                ('numero_pedido', models.CharField(max_length=20, unique=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
