# Generated by Django 4.2.4 on 2023-09-09 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apptelovendo', '0014_pedidocliente'),
    ]

    operations = [
        migrations.CreateModel(
            name='NumeroPedidoUtilizado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_pedido', models.CharField(max_length=10, unique=True)),
            ],
        ),
        migrations.AlterField(
            model_name='pedidocliente',
            name='numero_pedido',
            field=models.CharField(editable=False, max_length=10, unique=True),
        ),
    ]
