# Generated by Django 4.2.4 on 2023-09-09 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apptelovendo', '0015_numeropedidoutilizado_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedidocliente',
            name='fecha_pedido',
            field=models.DateField(),
        ),
    ]
