# Generated by Django 4.2.4 on 2023-09-09 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apptelovendo', '0016_alter_pedidocliente_fecha_pedido'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pedidocliente',
            name='usuario',
        ),
        migrations.AddField(
            model_name='pedidocliente',
            name='cliente',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
