# Generated by Django 4.2.4 on 2023-09-10 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apptelovendo', '0018_pedidocliente_cantidad'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedidocliente',
            name='productos',
            field=models.ManyToManyField(to='apptelovendo.producto'),
        ),
    ]
