# Generated by Django 4.2.4 on 2023-09-11 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apptelovendo', '0019_pedidocliente_productos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('preparacion', 'En preparacion'), ('despacho', 'En despacho'), ('entregado', 'Entregado'), ('cancelado', 'Cancelado')], max_length=20),
        ),
    ]
