# Generated by Django 4.2.4 on 2023-09-11 17:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apptelovendo', '0020_alter_pedido_estado'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistorialPedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(max_length=20)),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apptelovendo.pedidocliente')),
            ],
        ),
    ]
