# Generated by Django 4.2.4 on 2023-09-11 19:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apptelovendo', '0021_historialpedido'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='pedido_cliente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pedidos', to='apptelovendo.pedidocliente'),
        ),
    ]
