# Generated by Django 4.2.4 on 2023-09-13 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apptelovendo', '0022_pedido_pedido_cliente'),
    ]

    operations = [
        migrations.AddField(
            model_name='historialpedido',
            name='etsado_actual',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
