# Generated by Django 4.2.4 on 2023-09-14 00:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apptelovendo', '0023_historialpedido_etsado_actual'),
    ]

    operations = [
        migrations.RenameField(
            model_name='historialpedido',
            old_name='etsado_actual',
            new_name='estado_actual',
        ),
    ]
