# Generated by Django 4.2.4 on 2023-09-14 18:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apptelovendo', '0024_rename_etsado_actual_historialpedido_estado_actual'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pedido',
            name='pedido_cliente',
        ),
        migrations.AddField(
            model_name='pedidocliente',
            name='estado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='apptelovendo.pedido'),
        ),
    ]
